apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: math-add
            image: ubuntu
            command: ["expr", '3', '+', '2']
          restartPolicy: Never
  schedule: "*/1 * * * *"
