apiVersion: v1
data:
  key1: c3VwZXJzZWNyZXQ=
kind: Secret
metadata:
  creationTimestamp: "2024-06-17T04:35:02Z"
  name: my-secret
  namespace: default
  resourceVersion: "25352"
  uid: 33ec6510-e06c-4a63-8157-a3c6e35fe6f8
type: Opaque
